### ISSUE TITLE
Create a code style guide

### ISSUE THREAD

**Issue by slooths** [MintStudios/Signum#11]
**Is your feature request related to a problem? Please describe.**
This feature request would help keep the codebase clean and maintainable by enforcing a strict code style.

**Describe the solution you'd like**
The style guide would preferably include many similar or identical styles found in the [official GDScript style guide](https://docs.godotengine.org/en/3.2/getting_started/scripting/gdscript/gdscript_styleguide.html). This would include a [code order](https://docs.godotengine.org/en/3.2/getting_started/scripting/gdscript/gdscript_styleguide.html#code-order), [code formatting](https://docs.godotengine.org/en/3.2/getting_started/scripting/gdscript/gdscript_styleguide.html#formatting), [naming conventions](https://docs.godotengine.org/en/3.2/getting_started/scripting/gdscript/gdscript_styleguide.html#naming-conventions) for variables, methods and classes and perhaps also enforcing [static typing](https://docs.godotengine.org/en/3.2/getting_started/scripting/gdscript/gdscript_styleguide.html#static-typing).

The style guide could be a direct copy of the official GDScript style guide or a modified version. The most important thing is to make some sort of consistent guide for contributors to more easily read and write code.

**Describe alternatives you've considered**
Alternatives would simply be contributors writing code in different styles/conventions, potentially leading to more confusion for future contributors looking through older code.

**Comment by MintStudios** [comment]
Yes, this would be a good idea for contributors other than me.

**Comment by MintStudios** [comment]
I meant, this would be better for contributors to understand my code, but not for me, because I wrote it in my style.
