### ISSUE TITLE
Cannot open v0.2 in catalina

### ISSUE THREAD

**Issue by simkimsia** [MintStudios/Signum#18]
**Describe the bug**

![image](https://user-images.githubusercontent.com/245021/91851329-8f7d7b80-ec91-11ea-87dc-193707249730.png)

**Godot and Signum version**
0.2
godot 3.2.2
macos catalina 10.15.6

**To Reproduce**
download v0.2 after installing godot
install it
then try to open

**Comment by MintStudios** [comment]
Are you able to open up godot? And are on running the actual app for sigum, or is it being run directly from the editor?

**Comment by simkimsia** [comment]
![image](https://user-images.githubusercontent.com/245021/92113340-c08cb600-ee21-11ea-9e2a-f123b1e94c10.png)
s

then i click on Signum.app 
![image](https://user-images.githubusercontent.com/245021/92113400-d7cba380-ee21-11ea-9faf-1aab35e12227.png)

Then I get what you saw previously 

![image](https://user-images.githubusercontent.com/245021/92113440-e44ffc00-ee21-11ea-9b99-e6306e342ebd.png)

**Comment by MintStudios** [comment]
Can you try opening it from the terminal? Sometimes this works. If that doesn't work, try executing it directly from godot by cloning it.

**Comment by MintStudios** [comment]
I'm don't use macOS, but you should be able to open the app via the command line by navigating to the directory of signum.app, and then writing signum.app, which should open it up. If I wrote this in a hard to understand way, just search up how to open an app in terminal macos.

For running signum in godot, just download the source, scan it with godot, and open it up. From their, just run it from there like a normal game.

**Comment by simkimsia** [comment]
![image](https://user-images.githubusercontent.com/245021/92199840-ced2e480-eeaa-11ea-84ac-279d10bddea3.png)
This https://developer.apple.com/forums/thread/113291 tells me that you need to properly sign the app.

As for running it in godot

![image](https://user-images.githubusercontent.com/245021/92200029-54ef2b00-eeab-11ea-9b70-1ff33891b185.png)

**Comment by MintStudios** [comment]
Yes, so you would need to go into the project and run it from there, not from the project manager.

**Comment by simkimsia** [comment]
Ok i got it to work inside the Godot editor. Not sure if you wanna consider it as ticket closed. I leave it to you since technically it still doesn't work in mac OS as a standalone app.
