### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by KiwiFruit555** [MintStudios/Signum#22]
Could you add a light theme? Like white or something? I kind of want something like iOS theme.. With light colors and rounded... It would be easy, especially if you have an actual iOS to get the colors from.

And also, there wouldn't be a way to get the theme from Windows 10, would there? I think that would be cool...

**Comment by MintStudios** [comment]
@KiwiFruit555 sorry for this late response, but LibreSprite is made to look, well, pixel-y. iOS is the complete opposite with rounded everything. If you just want different colors, I think @maujin111 has created/ported a theme for LiberSprite.

**Comment by StarlkYT** [comment]
I think there's already a theme that has white colors with rounded edges.

**Comment by MintStudios** [comment]
@StarlkYT I was working on that a bit ago. I can't insure full system theming, but it still has an ios look and feel now.

**Comment by StarlkYT** [comment]
I think it's safe to delete the issue then.
