### ISSUE TITLE
[UI] Tree Panel Got Messed Up when Clicking on Expander

### ISSUE THREAD

**Issue by chaojian-zhang** [MintStudios/Signum#24]
**Describe the bug**

When you click on Tree panel's current folder label, navigation stops working.

**Godot and Signum version**

* Godot Engine v3.2.3.stable.mono.official
* Signum doesn't have a version code but I am using the latest

**To Reproduce**
1. Open any file
2. Click on the current folder label
3. Try click on any folder
4. Current folder label updates but folder tree are not updated

**Expected behavior**

After clicking on the current folder label, folder tree navigation shouldn't be affected.

**Screenshots**

Please see a video demonstrating this issue: https://youtu.be/6W67JXRfQfI

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro

**Comment by MintStudios** [comment]
Fixed with pull request #25
