### ISSUE TITLE
Switch to godot 3.2.2 ?

### ISSUE THREAD

**Issue by superRaptor911** [MintStudios/Signum#7]
Switching to godot 3.2.2 may improve performance .

**Comment by MintStudios** [comment]
Yes, it will probably be better, even though it might not boost performance, it will be the standard for a lot of users of Godot.

**Comment by superRaptor911** [comment]
Yes. No need to port anything , it works as it is in godot 3.2.2

**Comment by superRaptor911** [comment]
What about my pull request, do i need to change anything?

**Comment by superRaptor911** [comment]
Done
